name: Create Backend Branch
on:
  push:	
    branches:	
      - dev_dinh
    paths:
      - 'Backend'
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Deploy Backend
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: backend
        FOLDER: Backend
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
