name: Create Frontend Branch
on:
  push:	
    branches:	
      - main
    paths:
      - 'Frontend'
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@main
      with:
        token: ${{secrets.PAT}}
    - name: Deploy Frontend
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: frontend
        FOLDER: Frontend
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
